# Use a separate output directory for each training seed.
ALG: IPPO_RNN_NoPS
ACTIVATION: relu
GRU_HIDDEN_DIM: 128
FC_DIM_SIZE: 128
ENV_NAME: hanabi
ENV_KWARGS:
  num_agents: 2
TOTAL_TIMESTEPS: 1e10
NUM_STEPS: 128
NUM_ENVS: 1024
SEED: 30
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
ANNEAL_LR: true
LR: 5e-4
ENT_COEF: 0.01
CLIP_EPS: 0.2
SCALE_CLIP_EPS: false
GAMMA: 0.99
GAE_LAMBDA: 0.95
VF_COEF: 1.0
MAX_GRAD_NORM: 0.5
ADAM_EPS: 1e-8
TEST_DURING_TRAINING: false
TEST_INTERVAL: 0.05
TEST_NUM_STEPS: 128
TEST_NUM_ENVS: 32
DISABLE_JIT: false
