# Use a separate output directory for each training seed.
ALG: IPPO_RNN_NoPS
FC_DIM_SIZE: 128
GRU_HIDDEN_DIM: 128
SCALE_CLIP_EPS: false
LR: 1e-3
NUM_ENVS: 64
NUM_STEPS: 300
TOTAL_TIMESTEPS: 1e8
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 2e-6
VF_COEF: 4.5
MAX_GRAD_NORM: 0.5
ACTIVATION: tanh
SEED: 30
ENV_NAME: ant_4x2
ENV_KWARGS:
  homogenisation_method: null
ANNEAL_LR: true
DISABLE_JIT: false
TEST_DURING_TRAINING: false
TEST_INTERVAL: 0.05
TEST_NUM_STEPS: 1000
TEST_NUM_ENVS: 32
CONTINUOUS_ACTIONS: true
