# Use a separate output directory for each training seed.
ALG: MAPPO_FF_NoPS
LR: 5e-4
NUM_ENVS: 1024
NUM_STEPS: 128
TOTAL_TIMESTEPS: 1e10
FC_DIM_SIZE: 128
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: relu
ENV_NAME: hanabi
ENV_KWARGS:
  num_agents: 2
ANNEAL_LR: true
SEED: 30
SCALE_CLIP_EPS: false
ADAM_EPS: 1e-8
DISABLE_JIT: false
TEST_DURING_TRAINING: false
TEST_INTERVAL: 0.1
TEST_NUM_STEPS: 100
TEST_NUM_ENVS: 32
